CREATE TABLE "APP".PAYMENTS (
	ORDERID INTEGER NOT NULL,
	USERID INTEGER NOT NULL,
	AMOUNT DOUBLE NOT NULL,
	DATE DATE DEFAULT CURRENT_DATE NOT NULL,
	TYPE VARCHAR(20) DEFAULT 'WALLET' NOT NULL,
	STATUS VARCHAR(20) DEFAULT 'SUBMITTED' NOT NULL,
	PAYMENTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CONSTRAINT primaryKey PRIMARY KEY (PAYMENTID),
	CONSTRAINT chkType CHECK (TYPE IN ('WALLET','CREDIT_CARD','BANK_TRANSFER','PAYPAL')),
	CONSTRAINT chkStatus CHECK (STATUS IN ('SUBMITTED','SAVED','PROCESSING','ACCEPTED','DECLINED'))
);
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT) VALUES ('1','1','10.00');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('2','2','20.00','CREDIT_CARD','SAVED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('3','3','30.00','BANK_TRANSFER','PROCESSING');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('4','4','40.00','PAYPAL','DECLINED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('5','5','50.00','WALLET','ACCEPTED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT) VALUES ('6','6','60.00');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('7','7','70.00','CREDIT_CARD','SAVED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('8','8','80.00','BANK_TRANSFER','PROCESSING');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('9','9','90.00','PAYPAL','DECLINED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('10','10','100.00','WALLET','ACCEPTED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT) VALUES ('11','11','110.00');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('12','12','120.00','CREDIT_CARD','SAVED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('13','13','130.00','BANK_TRANSFER','PROCESSING');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('14','14','140.00','PAYPAL','DECLINED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('15','15','150.00','WALLET','ACCEPTED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT) VALUES ('16','16','160.00');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('17','17','170.00','CREDIT_CARD','SAVED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('18','18','180.00','BANK_TRANSFER','PROCESSING');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('19','19','190.00','PAYPAL','DECLINED');
INSERT INTO PAYMENTS (ORDERID,USERID,AMOUNT,TYPE,STATUS) VALUES ('20','20','200.00','WALLET','ACCEPTED');